services:
  - type: web
    name: waste-classifier
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "2"  # Reduce TensorFlow logging 